# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L,XL', help_text='Comma-separated list of sizes like S,M,L,XL', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
